# Generated by Django 5.2.8 on 2025-12-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loan_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_loan', to='app.loanapplication'),
        ),
    ]
