# Generated by Django 5.2.8 on 2025-12-03 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loan_options_loan_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
