# Generated by Django 5.2.8 on 2025-12-03 20:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_loan_options_loan_funded_date_loan_lender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5),
        ),
    ]
