# Generated by Django 5.2.8 on 2025-12-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='monthly_payment',
        ),
    ]
