# Generated by Django 5.2.8 on 2025-12-03 20:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_loan_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
