# Generated by Django 5.2.8 on 2025-12-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_loanpayment_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpayment',
            old_name='borrower',
            new_name='user',
        ),
    ]
