# Generated by Django 5.2.8 on 2025-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_notification_title_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], max_length=20),
        ),
    ]
